### ISSUE TITLE
Bluetooth doesn't work on HP 15-rb004nt

### ISSUE THREAD

**Issue by windowz414** [supremegamers/darkmatter#13]
**Describe the bug**
Bluetooth simply doesn't turn on.

**To Reproduce**
1. Settings > Bluetooth
2. Try to toggle it on.
3. The toggle will grey out and won't turn on.

**Expected behavior**
Bluetooth turns on and works properly.

**Desktop (please complete the following information):**
 - CPU: AMD A4-9120 APU (2 Compute Cores, 2 Graphics Cores)
 - GPU: iGPU, AMD Radeon R3 Graphics
 - BIOS: UEFI
 - TYPE: Laptop

**GearDump logs**
[geardump.zip](https://github.com/supremegamers/darkmatter/files/9748513/geardump.zip)

**Additional context**
This issue would commonly happen with the WiFi adapter on pretty much all Android-x86 derivatives I would've tried. I presume this is either a missing firmware or kernel module just like what I had on Debian before. Checking the logcat, there seems to be nothing related to Bluetooth at all so I presume I need to build my own custom kernel with the module embedded in? The Bluetooth dongle is laptop's stock one and it works on pretty much all GNU/Linux distros shipping with Linux 5.11 and later, if I wouldn't count Windows. Some distros would backport the drivers from there to older versions or simply write their own before it was fixed on Linux itself before. The brand of dongle is Realtek AFAIK, but I'm not so sure if it really is, I need to reboot to Windows and check it again.

**Screenshots**
![Screenshot_20221010-224534](https://user-images.githubusercontent.com/39265461/194941450-2f26eaa6-8b08-4b7e-ad36-9979d7b4b35e.jpg)

**Comment by hmtheboy154** [comment]
the 7.x stack is suck, pls upgrade to BlissOS 14.10

**Comment by windowz414** [comment]
> the 7.x stack is suck, pls upgrade to BlissOS 14.10

And where can I report bugs I face on it?

**Comment by hmtheboy154** [comment]
14.10 ? On BlissOS Telegram or Discord

**Comment by windowz414** [comment]
> 14.10 ? On BlissOS Telegram or Discord

Alright, thanks!
